[[pages]]
path = "Home_Page.py"
name = "Home"
icon = "ğŸ "


[[pages]]
path = "ChatbotOpenAI.py"
name = "AI Tutor"
icon = "ğŸ§‘ğŸ½â€ğŸ’»"

[[pages]]
path = "problem_code.py"
name = "Problem-Code Matching"
icon = "âœ¨"


[[pages]]
path = "Quiz.py"
name = "DS Quiz"
icon = "â“"

[[pages]]
path = "Admin_Panel.py"
name = "Admin Panel"
icon = "ğŸ› ï¸"




