[[pages]]
path = "Home_Page.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "Chatbot.py"
name = "Chatbot Gemini"
icon = "ğŸ¤–"

[[pages]]
path = "ChatbotOpenAI.py"
name = "Chatbot OpenAI"
icon = "ğŸ§‘ğŸ½â€ğŸ’»"

[[pages]]
path = "Quiz.py"
name = "DS Quiz"
icon = "â“"

[[pages]]
path = "Admin_Panel.py"
name = "Admin Panel"
icon = "ğŸ› ï¸"


